language: python

python:
  - '3.7'

os:
  - linux

addons:
  apt:
    packages:
      - python3-pyqt5
      
before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest

  # Install codeclimate API
  # https://docs.codeclimate.com/
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - coverage run -m pytest
  - coverage xml

after_script:
  # So that we can read off test coverage from the travis build
  - coverage report
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
